/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsTaskassistRouteImport } from './routes/products.taskassist'
import { Route as ProductsQaassistRouteImport } from './routes/products.qaassist'
import { Route as ProductsLinkassistRouteImport } from './routes/products.linkassist'
import { Route as ProductsHireassistRouteImport } from './routes/products.hireassist'
import { Route as ProductsCoachassistRouteImport } from './routes/products.coachassist'
import { Route as ProductsAttributionRouteImport } from './routes/products.attribution'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTaskassistRoute = ProductsTaskassistRouteImport.update({
  id: '/taskassist',
  path: '/taskassist',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsQaassistRoute = ProductsQaassistRouteImport.update({
  id: '/qaassist',
  path: '/qaassist',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsLinkassistRoute = ProductsLinkassistRouteImport.update({
  id: '/linkassist',
  path: '/linkassist',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsHireassistRoute = ProductsHireassistRouteImport.update({
  id: '/hireassist',
  path: '/hireassist',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCoachassistRoute = ProductsCoachassistRouteImport.update({
  id: '/coachassist',
  path: '/coachassist',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsAttributionRoute = ProductsAttributionRouteImport.update({
  id: '/attribution',
  path: '/attribution',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/products/attribution': typeof ProductsAttributionRoute
  '/products/coachassist': typeof ProductsCoachassistRoute
  '/products/hireassist': typeof ProductsHireassistRoute
  '/products/linkassist': typeof ProductsLinkassistRoute
  '/products/qaassist': typeof ProductsQaassistRoute
  '/products/taskassist': typeof ProductsTaskassistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/products/attribution': typeof ProductsAttributionRoute
  '/products/coachassist': typeof ProductsCoachassistRoute
  '/products/hireassist': typeof ProductsHireassistRoute
  '/products/linkassist': typeof ProductsLinkassistRoute
  '/products/qaassist': typeof ProductsQaassistRoute
  '/products/taskassist': typeof ProductsTaskassistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/products/attribution': typeof ProductsAttributionRoute
  '/products/coachassist': typeof ProductsCoachassistRoute
  '/products/hireassist': typeof ProductsHireassistRoute
  '/products/linkassist': typeof ProductsLinkassistRoute
  '/products/qaassist': typeof ProductsQaassistRoute
  '/products/taskassist': typeof ProductsTaskassistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/products'
    | '/services'
    | '/team'
    | '/products/attribution'
    | '/products/coachassist'
    | '/products/hireassist'
    | '/products/linkassist'
    | '/products/qaassist'
    | '/products/taskassist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/products'
    | '/services'
    | '/team'
    | '/products/attribution'
    | '/products/coachassist'
    | '/products/hireassist'
    | '/products/linkassist'
    | '/products/qaassist'
    | '/products/taskassist'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/products'
    | '/services'
    | '/team'
    | '/products/attribution'
    | '/products/coachassist'
    | '/products/hireassist'
    | '/products/linkassist'
    | '/products/qaassist'
    | '/products/taskassist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/taskassist': {
      id: '/products/taskassist'
      path: '/taskassist'
      fullPath: '/products/taskassist'
      preLoaderRoute: typeof ProductsTaskassistRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/qaassist': {
      id: '/products/qaassist'
      path: '/qaassist'
      fullPath: '/products/qaassist'
      preLoaderRoute: typeof ProductsQaassistRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/linkassist': {
      id: '/products/linkassist'
      path: '/linkassist'
      fullPath: '/products/linkassist'
      preLoaderRoute: typeof ProductsLinkassistRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/hireassist': {
      id: '/products/hireassist'
      path: '/hireassist'
      fullPath: '/products/hireassist'
      preLoaderRoute: typeof ProductsHireassistRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/coachassist': {
      id: '/products/coachassist'
      path: '/coachassist'
      fullPath: '/products/coachassist'
      preLoaderRoute: typeof ProductsCoachassistRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/attribution': {
      id: '/products/attribution'
      path: '/attribution'
      fullPath: '/products/attribution'
      preLoaderRoute: typeof ProductsAttributionRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsAttributionRoute: typeof ProductsAttributionRoute
  ProductsCoachassistRoute: typeof ProductsCoachassistRoute
  ProductsHireassistRoute: typeof ProductsHireassistRoute
  ProductsLinkassistRoute: typeof ProductsLinkassistRoute
  ProductsQaassistRoute: typeof ProductsQaassistRoute
  ProductsTaskassistRoute: typeof ProductsTaskassistRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsAttributionRoute: ProductsAttributionRoute,
  ProductsCoachassistRoute: ProductsCoachassistRoute,
  ProductsHireassistRoute: ProductsHireassistRoute,
  ProductsLinkassistRoute: ProductsLinkassistRoute,
  ProductsQaassistRoute: ProductsQaassistRoute,
  ProductsTaskassistRoute: ProductsTaskassistRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
