/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ServicesBusinessAuditRouteImport } from './routes/services.business-audit'
import { Route as ServicesBdaOsImplementationRouteImport } from './routes/services.bda-os-implementation'
import { Route as ServicesAiTrainingRouteImport } from './routes/services.ai-training'
import { Route as ProductsTaskassistRouteImport } from './routes/products.taskassist'
import { Route as ProductsQaassistRouteImport } from './routes/products.qaassist'
import { Route as ProductsLinkassistRouteImport } from './routes/products.linkassist'
import { Route as ProductsHireassistRouteImport } from './routes/products.hireassist'
import { Route as ProductsCoachassistRouteImport } from './routes/products.coachassist'
import { Route as ProductsAttributionRouteImport } from './routes/products.attribution'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBusinessAuditRoute = ServicesBusinessAuditRouteImport.update({
  id: '/services/business-audit',
  path: '/services/business-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBdaOsImplementationRoute =
  ServicesBdaOsImplementationRouteImport.update({
    id: '/services/bda-os-implementation',
    path: '/services/bda-os-implementation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAiTrainingRoute = ServicesAiTrainingRouteImport.update({
  id: '/services/ai-training',
  path: '/services/ai-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTaskassistRoute = ProductsTaskassistRouteImport.update({
  id: '/products/taskassist',
  path: '/products/taskassist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsQaassistRoute = ProductsQaassistRouteImport.update({
  id: '/products/qaassist',
  path: '/products/qaassist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsLinkassistRoute = ProductsLinkassistRouteImport.update({
  id: '/products/linkassist',
  path: '/products/linkassist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHireassistRoute = ProductsHireassistRouteImport.update({
  id: '/products/hireassist',
  path: '/products/hireassist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCoachassistRoute = ProductsCoachassistRouteImport.update({
  id: '/products/coachassist',
  path: '/products/coachassist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAttributionRoute = ProductsAttributionRouteImport.update({
  id: '/products/attribution',
  path: '/products/attribution',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/team': typeof TeamRoute
  '/products/attribution': typeof ProductsAttributionRoute
  '/products/coachassist': typeof ProductsCoachassistRoute
  '/products/hireassist': typeof ProductsHireassistRoute
  '/products/linkassist': typeof ProductsLinkassistRoute
  '/products/qaassist': typeof ProductsQaassistRoute
  '/products/taskassist': typeof ProductsTaskassistRoute
  '/services/ai-training': typeof ServicesAiTrainingRoute
  '/services/bda-os-implementation': typeof ServicesBdaOsImplementationRoute
  '/services/business-audit': typeof ServicesBusinessAuditRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/team': typeof TeamRoute
  '/products/attribution': typeof ProductsAttributionRoute
  '/products/coachassist': typeof ProductsCoachassistRoute
  '/products/hireassist': typeof ProductsHireassistRoute
  '/products/linkassist': typeof ProductsLinkassistRoute
  '/products/qaassist': typeof ProductsQaassistRoute
  '/products/taskassist': typeof ProductsTaskassistRoute
  '/services/ai-training': typeof ServicesAiTrainingRoute
  '/services/bda-os-implementation': typeof ServicesBdaOsImplementationRoute
  '/services/business-audit': typeof ServicesBusinessAuditRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/team': typeof TeamRoute
  '/products/attribution': typeof ProductsAttributionRoute
  '/products/coachassist': typeof ProductsCoachassistRoute
  '/products/hireassist': typeof ProductsHireassistRoute
  '/products/linkassist': typeof ProductsLinkassistRoute
  '/products/qaassist': typeof ProductsQaassistRoute
  '/products/taskassist': typeof ProductsTaskassistRoute
  '/services/ai-training': typeof ServicesAiTrainingRoute
  '/services/bda-os-implementation': typeof ServicesBdaOsImplementationRoute
  '/services/business-audit': typeof ServicesBusinessAuditRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/team'
    | '/products/attribution'
    | '/products/coachassist'
    | '/products/hireassist'
    | '/products/linkassist'
    | '/products/qaassist'
    | '/products/taskassist'
    | '/services/ai-training'
    | '/services/bda-os-implementation'
    | '/services/business-audit'
    | '/products/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/team'
    | '/products/attribution'
    | '/products/coachassist'
    | '/products/hireassist'
    | '/products/linkassist'
    | '/products/qaassist'
    | '/products/taskassist'
    | '/services/ai-training'
    | '/services/bda-os-implementation'
    | '/services/business-audit'
    | '/products'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/team'
    | '/products/attribution'
    | '/products/coachassist'
    | '/products/hireassist'
    | '/products/linkassist'
    | '/products/qaassist'
    | '/products/taskassist'
    | '/services/ai-training'
    | '/services/bda-os-implementation'
    | '/services/business-audit'
    | '/products/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  TeamRoute: typeof TeamRoute
  ProductsAttributionRoute: typeof ProductsAttributionRoute
  ProductsCoachassistRoute: typeof ProductsCoachassistRoute
  ProductsHireassistRoute: typeof ProductsHireassistRoute
  ProductsLinkassistRoute: typeof ProductsLinkassistRoute
  ProductsQaassistRoute: typeof ProductsQaassistRoute
  ProductsTaskassistRoute: typeof ProductsTaskassistRoute
  ServicesAiTrainingRoute: typeof ServicesAiTrainingRoute
  ServicesBdaOsImplementationRoute: typeof ServicesBdaOsImplementationRoute
  ServicesBusinessAuditRoute: typeof ServicesBusinessAuditRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business-audit': {
      id: '/services/business-audit'
      path: '/services/business-audit'
      fullPath: '/services/business-audit'
      preLoaderRoute: typeof ServicesBusinessAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bda-os-implementation': {
      id: '/services/bda-os-implementation'
      path: '/services/bda-os-implementation'
      fullPath: '/services/bda-os-implementation'
      preLoaderRoute: typeof ServicesBdaOsImplementationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-training': {
      id: '/services/ai-training'
      path: '/services/ai-training'
      fullPath: '/services/ai-training'
      preLoaderRoute: typeof ServicesAiTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/taskassist': {
      id: '/products/taskassist'
      path: '/products/taskassist'
      fullPath: '/products/taskassist'
      preLoaderRoute: typeof ProductsTaskassistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/qaassist': {
      id: '/products/qaassist'
      path: '/products/qaassist'
      fullPath: '/products/qaassist'
      preLoaderRoute: typeof ProductsQaassistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/linkassist': {
      id: '/products/linkassist'
      path: '/products/linkassist'
      fullPath: '/products/linkassist'
      preLoaderRoute: typeof ProductsLinkassistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/hireassist': {
      id: '/products/hireassist'
      path: '/products/hireassist'
      fullPath: '/products/hireassist'
      preLoaderRoute: typeof ProductsHireassistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/coachassist': {
      id: '/products/coachassist'
      path: '/products/coachassist'
      fullPath: '/products/coachassist'
      preLoaderRoute: typeof ProductsCoachassistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/attribution': {
      id: '/products/attribution'
      path: '/products/attribution'
      fullPath: '/products/attribution'
      preLoaderRoute: typeof ProductsAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  TeamRoute: TeamRoute,
  ProductsAttributionRoute: ProductsAttributionRoute,
  ProductsCoachassistRoute: ProductsCoachassistRoute,
  ProductsHireassistRoute: ProductsHireassistRoute,
  ProductsLinkassistRoute: ProductsLinkassistRoute,
  ProductsQaassistRoute: ProductsQaassistRoute,
  ProductsTaskassistRoute: ProductsTaskassistRoute,
  ServicesAiTrainingRoute: ServicesAiTrainingRoute,
  ServicesBdaOsImplementationRoute: ServicesBdaOsImplementationRoute,
  ServicesBusinessAuditRoute: ServicesBusinessAuditRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
